---
title: "Reflections-First Cycle Coding"
subtitle: "Processing and In Vivo Methods"
author: "Kara Brick"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r ref.label=knitr::all_labels(), setup, include=FALSE}
library(tufte)
library(tibble)
library(readxl)
library(dplyr)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
df <- read_excel('Reflections.xlsx')
```
Paticipants: Teachers in Monrovia, Liberia   
Site: Five day workshop using a neuroscience and trauma-informed teaching framework to build relationnships and improve learning outcomes    
Date: December 2018.    

# Day 1 Reflections, 1st question
Prompts for Day 1 begin with "What did you learn?" Respondents write their answers and turn in to facilitators at the end of each day. 
[1] "Few of the things that I learn today as follow: a) mental health is not all about madness.^[reducing stigma] It can be cause by many factors social, economic, etc.^[defining causes of mental health issues] I also learn about addiction, I got to know that addiction is not just about drug or alcohol but other things that we make as habit.^[expanding addiction definition] "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 [2] "I learned about the brain and spinal cord which is the central point of the body and controls all activities of the body.^[Learning about neuroscience] This part which is the brain contain a system known as nervous system that carries messages throughout the body which are tasting, feeling, hearing, etc^[Learning about neurotransmission]. Also I got to know about mental health problems."                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [3] "I learned how communication is transmitted through the nervous system,^[Learning about neurotransmission] the preparation of the neuron beads,^[learning a hands-on activity/student-centered activty] how people get addicted to negative substances and how they get out of it.^["Addiction- how they get out of it."]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 [4] "I was apply to learn about mental health and its effects and how to solve it including to drug abuse and its effects.^[Learning about recovery] "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 [5] "I now know what is neuroscience, I have to learn how the brain receives signals, process signasl for quick response.^[Learning neurotransmission] Further I have understand what is mental health and the various challenges facing people with mental health and how to help people of such situations." ^[Reducing stigma / Increasing knowledge of MH]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 [6] "Today I learn about the breadth of neuroscience, how the CNS and PNS ^[Learning about nervous systems]function and how mental health can be cause and how can they be handle.^[Adressing mental health issues] I also learn how to make a neuron and the blind sport how does the brain works. "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 [7] "I learned more about neurotransmitter, on how the brain help us to make our life improved." ^["The brain help us to make our life improved"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 [8] "It was really great being part of today's activities. The lecture sessions on mental health was rewarding. I realized mental health is not about madness or craziness.^[destigmatizing mental illness] But a condition where in individuals can be come for by parents, friends and relatives. ^[Learning about mental health genetics] Mental health from what I learnt, must be serious seen as a physical disease by Africans instead of curse, God's wrath, witchcraft or demons problems.^[destigmatizing mental illness/western context] In addition, we were able to understand the nervous system and how nerve cells or neurons play a major role in the function of CNS (Brain and Spinal Cord). Finally, the video on drugs addiction climax the entire neuroscience workshop for today. I learnt drugs addiction does not solve any problems we are faced with, but makes it worse and even destroys our future." ^[seeing drugs as a bad solution to life's problems]
 [9] "I learned nervous system being a system that allows you to experience things and react to your environment.^[learning neuroscience] The brain being central most important part of our body. I also learned about the three parts of the brain as the cerebellum, the cerebrum, and the brain stem. I also learned that those having mental illness should be taking care of.^[shifting societal perspective of responsibility for mental health] And those addicted to certain behaviors change because of their conscience."^[demoralizing addiction]         
^[##Note: Participants spent the first day of the workshop learning basic and in depth neuroscience and anatomy followed by the addiction episode of 'The Red Table Talk' which was chosen to represent Black America and destigmatize addiction.]

[10] "I learned lots of things. Today, like, mental illness, brain function, and addiction."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[11] "I learned that mental health problems is not really different from madness but we should not discriminate them, but rather help them to be recovered.^[destigmatizing mental illness, valuing recovery and rehabilitation] I also learned how to prepared the nerve cell hands on." ^[Learning a hands-on or student-centered activity]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
[12] "I learned additional responsibilities as a teacher, how the neuron works, and practically preparing a neuron using beads and thread,^[learning hands-on/student centered activities] and finally how addiction become partr of a person's activities and how it can be avoided." ^[avoiding addiction]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
[13] "I came in very late in the last session about drug addiction. "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
[14] "I learned a lot today about the brain function that includes: - the nervous system, consisting of the central nervous system and the peripheral nerve system. The central nerve system is located in the brain and spinal cord, while the peripheral nerve system is located in the trunk of the body. The response of the body to stimuli (jerks) is done by a process called reflex. Neuroscience is a new way of study the human brain function and coping with mental illness or people with mental illness condition."^[Learning neuroscience as a framework for mentall illness]                                                                                                                                                                                                                                                                         
[15] "I learned a lot about drugs and substance abuse, it affect especially the brain because neuron sends it's information from one cell to another.^[connecting neuroscience and substance use] Drugs and substance abuse effect one's life but it essential that we can incorporate them in to society." ^[destigmatizing addiction?]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[16] "I learn about how to talk to those that take in weed. Out talking can make them to change." ^[engaging substance users as a means to recovery]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[17] "I learn today on neuroscience, the process of nerve transmission, from the brain to the other branches of nerves. The process of transport of communication or information.^[learning neurotransmission,anatomy] I also learned about drugs addiction, which younger people are seriously addicted to, and it is also destroying their nerves cell and its function."^[connecting between neuroscience and substance use]                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
[18] "Learned that mental health people are important to or in the society. ^[destigmatizing mental illness] Also learned about substance abuse, drug addiction, how one get addicted to drug from parents or guardian from home.^[identifying the sources of addiction] Identified part of the brain, how messages are passed on from the neurons and to the brain and body cells.^[learning neurotransmission] "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[19] "I learned about the breadth of the nervous system and how to take care of mad people." ^[learning neuroscience and destigmatizing mental illness]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                      