---
title: "Reflections-First Cycle Coding"
subtitle: "Processing and In Vivo Methods"
author: "Kara Brick"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r ref.label=knitr::all_labels(), setup, include=FALSE}
library(tufte)
library(tibble)
library(readxl)
library(dplyr)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
df <- read_excel('Reflections.xlsx')
```
Paticipants: Teachers in Monrovia, Liberia   
Site: Five day workshop using a neuroscience and trauma-informed teaching framework to build relationnships and improve learning outcomes    
Date: December 2018.   
Background: Liberia suffered through decades of civil wars until 2008, decimating the education system. Many teachers, a wealth of knowledge and experience, left or were killed. Literacy is low. Many are frustrated with slow post-conflict recovery. It is one of the poorest countries in the world. In the world happiness report, Liberia ranks 124 out of 153 (Helliwell, 2020). ^[Helliwell, J. F., Huang, H., Wang, S., & Norton, M. (2020). Social environments for world happiness. World Happiness Report 2020.]

### Day 1, 1st question: "What did you learn?"
 
[1] "Few of the things that I learn today as follow: a) mental health is not all about madness.^[reducing stigma, differentiating madness from normal mental spectra, "Not all about madness"] It can be cause by many factors social, economic, etc.^[defining causes of mental health issues] I also learn about addiction, I got to know that addiction is not just about drug or alcohol but other things that we make as habit.^[expanding addiction definition] "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 [2] "I learned about the brain and spinal cord which is the central point of the body and controls all activities of the body.^[Learning about neuroscience] This part which is the brain contain a system known as nervous system that carries messages throughout the body which are tasting, feeling, hearing, etc^[Learning about neurotransmission]. Also I got to know about mental health problems."                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [3] "I learned how communication is transmitted through the nervous system,^[Learning about neurotransmission] the preparation of the neuron beads,^[learning a hands-on activity/student-centered activty] how people get addicted to negative substances and how they get out of it.^["Addiction- how they get out of it."]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 [4] "I was apply to learn about mental health and its effects and how to solve it including to drug abuse and its effects.^[Learning about recovery] "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 [5] "I now know what is neuroscience, I have to learn how the brain receives signals, process signasl for quick response.^[Learning neurotransmission] Further I have understand what is mental health and the various challenges facing people with mental health and how to help people of such situations." ^[Reducing stigma / Increasing knowledge of MH]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 [6] "Today I learn about the breadth of neuroscience, how the CNS and PNS ^[Learning about nervous systems]function and how mental health can be cause and how can they be handle.^[Adressing mental health issues] I also learn how to make a neuron and the blind sport how does the brain works. "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 [7] "I learned more about neurotransmitter, on how the brain help us to make our life improved." ^["The brain help us to make our life improved"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 [8] "It was really great being part of today's activities. The lecture sessions on mental health was rewarding. I realized mental health is not about madness or craziness.^[destigmatizing mental illness] But a condition where in individuals can be come for by parents, friends and relatives. ^[Learning about mental health genetics] Mental health from what I learnt, must be serious seen as a physical disease by Africans instead of curse, God's wrath, witchcraft or demons problems.^[destigmatizing mental illness/western context] In addition, we were able to understand the nervous system and how nerve cells or neurons play a major role in the function of CNS (Brain and Spinal Cord). Finally, the video on drugs addiction climax the entire neuroscience workshop for today. I learnt drugs addiction does not solve any problems we are faced with, but makes it worse and even destroys our future." ^[seeing drugs as a bad solution to life's problems]
 [9] "I learned nervous system being a system that allows you to experience things and react to your environment.^[learning neuroscience] The brain being central most important part of our body. I also learned about the three parts of the brain as the cerebellum, the cerebrum, and the brain stem. I also learned that those having mental illness should be taking care of.^[shifting societal perspective of responsibility for mental health] And those addicted to certain behaviors change because of their conscience."^[demoralizing addiction]         
^[Note: Participants spent the first day of the workshop learning basic and in depth neuroscience and anatomy followed by the addiction episode of 'The Red Table Talk' which was chosen to represent Black America and destigmatize addiction.]

[10] "I learned lots of things. Today, like, mental illness, brain function, and addiction."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[11] "I learned that mental health problems is not really different from madness but we should not discriminate them, but rather help them to be recovered.^[destigmatizing mental illness, valuing recovery and rehabilitation] I also learned how to prepared the nerve cell hands on." ^[Learning a hands-on or student-centered activity]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
[12] "I learned additional responsibilities as a teacher, how the neuron works, and practically preparing a neuron using beads and thread,^[learning hands-on/student centered activities] and finally how addiction become partr of a person's activities and how it can be avoided." ^[avoiding addiction]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
[13] "I came in very late in the last session about drug addiction. "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
[14] "I learned a lot today about the brain function that includes: - the nervous system, consisting of the central nervous system and the peripheral nerve system. The central nerve system is located in the brain and spinal cord, while the peripheral nerve system is located in the trunk of the body. The response of the body to stimuli (jerks) is done by a process called reflex. Neuroscience is a new way of study the human brain function and coping with mental illness or people with mental illness condition."^[Learning neuroscience as a framework for mentall illness]                                                                                                                                                                                                                                                                         
[15] "I learned a lot about drugs and substance abuse, it affect especially the brain because neuron sends it's information from one cell to another.^[connecting neuroscience and substance use] Drugs and substance abuse effect one's life but it essential that we can incorporate them in to society." ^[destigmatizing addiction?]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[16] "I learn about how to talk to those that take in weed. Out talking can make them to change." ^[engaging substance users as a means to recovery]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[17] "I learn today on neuroscience, the process of nerve transmission, from the brain to the other branches of nerves. The process of transport of communication or information.^[learning neurotransmission,anatomy] I also learned about drugs addiction, which younger people are seriously addicted to, and it is also destroying their nerves cell and its function."^[connecting between neuroscience and substance use]                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
[18] "Learned that mental health people are important to or in the society. ^[destigmatizing mental illness] Also learned about substance abuse, drug addiction, how one get addicted to drug from parents or guardian from home.^[identifying the sources of addiction] Identified part of the brain, how messages are passed on from the neurons and to the brain and body cells.^[learning neurotransmission] "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[19] "I learned about the breadth of the nervous system and how to take care of mad people." ^[learning neuroscience and destigmatizing mental illness]   


### Day 1 Reflections, 2nd Question: "How will you apply this to your teaching?"   


[1] "As a teacher having learned these things I am going to apply it in the class with my students. That is tell them the danger of addiction ^[educating on addiction/warning] and also educate them about mental health." ^[destigmatizing mental health]                                                                                                                                                                                                                               
 [2] NA                                                                                                                                                                                                                                                                                                                                                                                                                   
 [3] "This has to do with the psychological responses of students in the classroom and the channel in apprehending the situation as a teacher." ^[thinking on your feet with new knowledge as a teacher]                                                                                                                                                                                                                                                                         
 [4] "This apply to my teaching in a way that I should be able to serve as a problem solver to such conditions if my students are in such a habit." ^[addressing addiction in the classroom]                                                                                                                                                                                                                                                                      
 [5] "This apply to my teaching to help advise ^[providing counsel] students that are found in such habit (addiction) and mental illness (depression from stress or trauma) to be of positive change and be fruitful in society."^[serving the community]                                                                                                                                                                                                          
 [6] "This will help me to more knowledge in my area of teaching and I will be able to help my students to settle make them to have passion for the course."^[using mental health literacy to improve learning outcomes]                                                                                                                                                                                                                                                             
 [7] "this will help me to teach the students to change from bad behavior to do something good for themselves." ^[changing course of student's lives]                                                                                                                                                                                                                                                                                                          
 [8] "In discharging our duties as teachers we find students in these categories: a. mental health problems b. drugs abuse/addiction. With the knowledge acquire today, I can apply this idea to students having mental health problems by relating to them positively and moreover ^[building relationships with struggling students], aid in saving students from drugs addiction by telling them the harmful effects of drugs/alcohols and how it worsen their problems." ^[addiction warning]
 [9] "It applies positively to my teaching in a sense that I have learned something new to help improve my class skill."                                                                                                                                                                                                                                                                                                 
[10] "It makes me to learn new things and to present new lessons and topics to my students. "                                                                                                                                                                                                                                                                                                                             
[11] "With the knowledge learned from the topics: mental health and addiction and substance abuse, I will be able to used them to help students know the dangers about substance use.^[addiction education/warning] I will also encourage them to avoid stigmatizing people that are suffering from mental illness."^[destigmatizing the classroom]                                                                                                                                   
[12] "This application of this to my teaching it it makes me to be more effective in dealing with students that have problem, whether from home, campus, addiction, etc."^[knowledge to solve problems]                                                                                                                                                                                                                                                
[13] "I understood that drugs are not good for the body. Drugs users always involve themselves in bad activities in a community. Many drug users do not listen ^["Many drug users do not listen"] good friend's advice concerning drug intake. They are advisors for themselves ^[advising themselves after ruining their lives] after they see the wrong actions for many years. As teachers we need to advise our students to avoid alcohol and drugs taking."^[addictiong warning, getting caught in drugs/no way out]                                             
[14] "In the classroom, there are students with different backgrounds and conditions of mental illness.^[seeing mental spectra of classroom] By attending this workshop and identifying these conditions, I can now be able to deal with them and encourage them that they are compare to any other students in the classroom."^[destigmatizing mental health issues]                                                                                                                                
[15] "I think this training apply a lot to my teaching in that I will be able to enlighten my students, the cause of drugs and substance. How does drugs and substance effect one's life." ^[addiction education]                                                                                                                                                                                                                               
[16] "It improves my teaching level."                                                                                                                                                                                                                                                                                                                                                                                    
[17] "This will help me as a teacher in order to carry on proper evaluation of my students, understand their sense of reasoning and their behavior toward classmate. And also solving their mental health problem, making them to be part of the society."^[addressing mental health in the classroom, benefitting the community]                                                                                                                                                               
[18] "Today teaching activities apply to numerous ways in my teaching, such as: learned how to deal with people with mental illness,^[addressing mental illness] learned how to deal with people who are addicted to drugs or substances and comfort those with mental illness and drugs addiction.^["comfort those with mental illness and drugs addiction"] Mainly learned what neuron science is all about (brain, spinal cord, nerves and so on)."                                                        
[19] "by knowing how to teach my students well and how to meet people around me." ^[including all students]                                                                                                                                                                                                                                                                                                                                        
[20] NA                                                                                                                                                                                                                                                                                                                                                                                                                   
[21] NA                                                                                                                                                                                               
   
## Day 1, 3rd question, "Why do you teach?"

[1] "I teach to transform lives,^["I teach to transorm lives"] that is impacting knowledge in my students in order to become good citizens in this society."^[impacting society]                                                                                                                                                    
 [2] NA                                                                                                                                                                                                                                                                            
 [3] "I teach because I love to pass on communication and knowledge to people that need it."^[loving to provide knowledge]                                                                                                                                                                                      
 [4] "I teach because I would like to correct ills in the society.^[correcting society] A teacher should always be ready to correct mistakes."^[always being ready]                                                                                                                                                         
 [5] "I teach to contribute to the society by modeling the minds of young people in the positive direction to be an ambassador of their families, communities, country and the world."^[changing communities through youth]                                                                                            
 [6] "I teach in order to help people to better understand their what they lack of and how can they become a greater person in society."^[helping people be better]                                                                                                                                          
 [7] "I teach to bring changes in life, for an individual to develop new idea."^[bringing changes, developing new ideas]                                                                                                                                                                                                   
 [8] "I teach because I love the profession^["I love the profession"] and to teach my students how to do right thing in order to achieve their goals."^[teaching people how to achieve]                                                                                                                                                      
 [9] "I teach because I'm interested in being a teacher."                                                                                                                                                                                                                         
[10] "I teach because I want to impact the lives of peoples and society."^[desiring to change society]                                                                                                                                                                                                         
[11] "I really teach to help people learn new things and to expose them to things that I know that they do not know, and also by other means learn somethings from them that I may not know."^[exchanging knowledge]                                                                                     
[12] "I teach to facilitate and built what a person/student has mentally for mental development which will make them grow in decision making."^[helping students grow intellectually]                                                                                                                                    
[13] NA                                                                                                                                                                                                                                                                            
[14] "I teach in order to bring positive change to society.^[change society] I have passion to teach because I feel like my knowledge is being passed on to the students and I learned from them in return.^[exchanging knowledge] I really can feel proud if my students are make headways out there."^["I really can feel proud", priding student achievement]                   
[15] "I teach to make people understand what I am teaching.^[teaching to understand] I teach to enlighten the minds of people.^[enlightening minds] I teach to make the mind of people to comprehend what I am teaching."^["make minds comprehend"]                                                                                                       
[16] "I teach because I want most children to be educated and to learn more."^[wanting children to be educated]                                                                                                                                                                                                     
[17] "It is the way to guide, conduct or training assesment for students."^[guiding students]                                                                                                                                                                                                        
[18] "There are many reasons: Have passion for what I have learned or I achieved to passed on^["passion for passing on knowledge"] to others, to educate and serves as rule model^[serving as role model] and agent to positive change to the young generations to come, finally to mold the mind to the younger generation for a better future"^[changing future through youth]
[19] "To make people know how to read and write^[increasing literacy] and to help make a new Liberia."^[Make a new Liberia]                                                                                                                           
[20] NA                                                                                                                                                                                                                                                                            
[21] NA                                                                                             ^[On reading, I wonder if references to teaching students 'the right way' and how to make decisions is in reference to bribery and avoiding corrupt future leaders through today's education system]
  
## Day 2, 1st Question, "What did you learn today?"

  
[1] "learn how to dissect a sheep brain, identified the parts of the brain (3 main parts) which cerebellum, which is the small brain, contains 4 lobes; the frontal lobe, parietal lobe, occipital love and temporal lobe, for auditory information and forming new membrane.^[learning anatomy through hands-on experience] Also learn that the brain is divided into right and left hemisphere, and the hippocampus for short term memory with the cerebral cortex for long term memory." ^[learning about intersection of neurofunction and anatomy]                                                                                                                                                                                                               
 [2] "I learn about dissection of brain by observing the various lobes.^[learning through observation] Frontal lobes - responsible for speech and planning. Temporal lobes- for hearing, occipital lobe for visual, parietal lobe for sense. ^[learning anatomy] Neurotransmitter - the chemical messenger in the human body. Synapse - the site of information. The process of transmission of ion exchange as positive charge in the cytoplasm and the negative which is known as hyperpolarization and depolarization.^[learning neuroscience process] Stress and emotional pressure that act on the human body."^["Stress and emotional pressure that act on the human body", stress and emotion acting as both internal and external force]                                                                                                                         
 [3] "I learned about the four types of brain and the definition of key terms, mechanisms of drug effects, communication in the brain.^[learning neuroscience processes and anatomy] This make me understand if someone is angry as a teacher I should be able to talk to help them with some of their problems."^[integrating trauma-informed teaching processes]                                                                                                                                                                                                                                                                                                                                                                                       
 [4] "The dissection of the sheep brain and discussing the various structures and functions of each parts. I also learn how information flows across the brain."^[learning neurotransmission and anatomy]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 [5] "today I learned about stress, how it treats the human body. Sometimes stress makes us sad, and even makes the body to get pain, and today I also know about the brain and it's parts."^["sometimes stress makes us sad" "how stress treats the human body", learning about stress, body, mind connection]                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [6] "I learn definition of key terms, initiating activities on sheep dissection (brain), video presentation, parts of the brain, location, neurotransmitter (chemical messengers), neurone and the parts of the neuron, its structure in terms of the diagram, stress (good and bad), classroom practices, optimal"^[bringing it all together into classroom practices]                                                                                                                                                                                                                                                                                                                                        
 [7] "there are physical and mental stress, good and bad stress, and also facial expression. ^[differentiating stress] Physical and mental stress are applied in the classroom when the teachers is not really feeling or putting himself in the learners shoes.^["stress in the classroom when teacher is not really putting himeslef in the learner's shoes"] Poor and don't care attitudees create physical and mental stress." ^["poor and don't care attitudes create physical and mental stress"]                                                                                                                                                                                                                                                                                                                                                 
 [8] "about the dissection of the sheep brain. I also learned how impulses are transmitted from the neurotransmitter to the dendrites^[learning neurotransmission] and the effect of stress on students in the classroom." ^[considering stress for students]                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 [9] "I learned about the three parts of the brain: Cerebrum, cerebellum, and the brain stem: midbrain, fore and hind brain. I learned how to dissect a sheep brain and other parts, such as gray matter and white matter, corpus collosum, longitudidinal fissure." ^[learning neuroanatomy through dissection]   
 [10] "Facial expression of people and how it relates to students that I'm teaching. That I should identify students by their facial expression and try to help them address problems they are faced with.^[reading students and applying trauma-informed teaching techniques] I learned about the neurons and the brain as the central and nerve activities. The brain is divided into three which is further divided into four lobes. The occipital (visual), parietal (sensation), frontal (speech) and temporal (auditory). ^[learning neuroanatomy] I learned to calculate my pulse rate by dividing the number of beat in 15 seconds by 4( since 15x4 is 1 minute). I also learned that the pulse rate increases with increase in stress."^[learning about stress interaction with body]         
[11] "I learn duties - functions and parts of the brain, practically identifying parts of the brain, how impulses (messages) are transmitted between neurons, to practically made a neuron, how to identify facial information and feelings, how to remove stress from students for motivational learning. "                                                                                                                                                                                                                                                                                                                                                
[12] "I learn on two things, today on sheep brain dissection and stress and also what stress can do." ^['what stress can do']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
[13] "the teaching today was very impressed because I learned more about the various part of the brain, also the functions.^[learning neuroanatomy and function] Also I learned about how to treat my students or learners when they are facing problem at home. Also learned how to motivate my learners when they are in class.^["motivating learners"] I also learned about stress and how we make students to go under stress by unannounced quiz or test and tension placed on students in class." [^"how we make students to go under stress"]                                                                                                                                                                                                                 
[14] "from the beginning of class we was able to dissect the brain of another mammal called sheep. Through the presentation, i understood that both the sheep and human brain have the same compartment that is divide into left and right hemisphere. Additionally, the brain is further divided into four lobes and they are frontal parietal occipital and temporal lobe. Furthermore, there there are also an organ that is connected to the brain called the spinal cord the resonsible to transmitted sensory information from the PNS.^[learning neuroanatomy and processing through dissectiong] We also spoke about stress, we see that there are two types of stress and they are mental and physical stress" ^[differentiating stress]
[15] "Today I learn about how to dissect the brain and to see the various part of it.^[learning how to dissect] I also learn about neurotransmittor how chemical and electrical material are transportated with in the neural system.^[learning neurotransmission] I also learn about the dendrites and how they are formed and how they work. I also learn about stress how as an individual we can deal with in time of a situation." ^[dealing with stress]                                                                                                                                                                                                                                                                           
[16] "I learn about sheep brain dissection"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
[17] "I learned about the brain. I learned about stress. I learned about facial expression. I learned to draw and design a neuron."           
[18] "I have the opportuntiy of hand touch of a sheep brain, where I was able to understand the various parts of the brain and their functions.^[learning neuroscience throught dissection] I learned about neurotransmitters, showing how informations flow through the brain firstly in electrical state and secondly into chemical state.^[learning neurotransmission] I learned about stress management and how to release stress off students and how to create class stress free."^[stress management in the classroom]                                                                                                                                                                                                                                             
[19] "I learned about the function and dissection of a sheep brain.^[learning dissection] It has the frontal lobe, parietal lobe, occipital lobe and temporal lobe.^[learning neuroanatomy] The gyri being the work like structure and the sulci being line on the brian. I also learned about the cause of stress for students and how to bring a stop to that."^[reducing stress for students]                                                                                                                                                                                                                                                                                                                                        
[20] NA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
[21] NA                                                                                             

## Day 2, 2nd Question, "How does it apply to your teaching?"

[1] "Going to apply to my teaching in the classrooom by during dissection in my classroom during my lab section."^[bringing dissection to the classroom]                                                                                                                                                                                                                                               
 [2] "The learn today with help me in the classroom to properly present by lesson very well, mostly dissection and stress, and the process of information transmission in human cells."                                                                                                                                                                        
 [3] NA                                                                                                                                                                                                                                                                                                                                                         
 [4] "This tell me as a teacher I need to involve my students in the lesson, by putting them in groups, pairs, etc. This will help them understand better."^[invloving students in the lesson, ^ increasing communication]                                                                                                                                                                                                    
 [5] "It add more knowledge to my teaching and improve my teaching also."                                                                                                                                                                                                                                                                                      
 [6] "This apply to my teaching daily in order to be optimal in working with my students collectively."^[inclusive teaching]                                                                                                                                                                                                                                                        
 [7] NA                                                                                                                                                                                                                                                                                                                                                         
 [8] "It creates a broader and in-depth understanding of what is learned from the literature and other class activities and also how to deal with those who you teach and interact with."                                                                                                                                                                      
 [9] "It empowers me to explain more to my students about the brain and its components and to avoid doing certain things that will cause damage to the brain. Today's lesson will also help me to always observe my students facial appearance so that I will discover some of the problems they face and how I can help handle some of them in the classroom."^[helping students with problems]
[10] NA                                                                                                                                                                                                                                                                                                                                                         
[11] "The application of this to my teaching is that will teach with practical being part, create an atmosphere in the classroom that will not stress the students."^[reducing stress in the classroom]                                                                                                                                                                                           
[12] "This also apply to my teaching as a tools to enable me teach the students to the best of their ability."^[changing content to fit more learning styles]                                                                                                                                                                                                                                                 
[13] NA                                                                                                                                                                                                                                                                                                                                                         
[14] NA                                                                                                                                                                                                                                                                                                                                                         
[15] "It will apply to your teaching in the positive aspect because from now I will know how I as individual to relate to my students and others with in my society."^[relating to others]                                                                                                                                                                                          
[16] "It helps me to improve my relationship with the students."^[building relationships]                                                                                                                                                                                                                                                                                               
[17] "It make me bring new ideas to my students."                                                                                                                                                                                                                                                                                                              
[18] "To my teaching this apply a lot, how to present my lesson in summary, let students do the discussion to bring out their own understanding ^[utilizing student-centered teaching techniques] of the topic under discussion while I the teacher is there to provide clarity and corrections of their errors."^[chaning roles in the classroom]                                                                                                
[19] "It has positively enlightened my teaching as per how to stress free my students and motivate them to learn more."^[reducing stress and motivating students]                                                                                                                                                                                                                                        
[20] NA                                                                                                                                                                                                                                                                                                                                                         
[21] NA  



## Day 2, Question #3, "Why do you teach?" 
 [1] "To mold the mind of the younger generation to form a better future."^["A better future"]                                                                                                                    
 [2] "We teach in order to guide, evaluate our students of what they have learned, in order to be part of them tomorrow."^["to be part of them tomorrow"]                                                                       
 [3] NA                                                                                                                                                                                          
 [4] "I teach to transform my students lives, to be good citizens in the society."^["transform lives"]                                                                                                              
 [5] "I want to educate children of Liberia."^["children of Liberia"]                                                                                                                                                   
 [6] NA                                                                                                                                                                                          
 [7] "We teach for the students to benefit for the future or to become future leaders."^[benefitting the future]                                                                                                         
 [8] "I teach in order to transfer knowledge to those who wants to know in the simplest form."^[transferring knowledge]                                                                                                  
 [9] "I actually teach to help students or other discover things they saw in time pass as good and health which is not actually the way they are. To also discover new ideas to solve problems."^[discovering new ideas]
[10] NA                                                                                                                                                                                          
[11] "I teach for students to learn new ideas and learn more of what they have achieved for their improvement."6[improving students]                                                                                 
[12] "I teach to improve the life of other who have learn into the society."^[improving society]                                                                                                                    
[13] NA                                                                                                                                                                                          
[14] NA                                                                                                                                                                                          
[15] "I teach because I have passion for the profession and I do believe that teaching will encourage me to educate people that will make our society better."^[bettering society]                                  
[16] "I teach in order to improve the lives of the children." ^[improving lives of children]                                                                                                                                  
[17] "I teach because I want to make my next generation better and impact lives."^[bettering the next generation]                                                                                                               
[18] "To have interactive learning center with students they may have ideas that I the teacher don't know, to share my own experiences with students and make a positive impact on their lives."^[centering learning on interaction, creating positive impact, sharing experience]
  
[19] "I teach because teaching is my area of specialization."                                                                                                                                   
[20] NA                                                                                                                                                                                          
[21] NA 

## Day 3, Question 1, "What did you learn today?"

[1] "I learned about neuroscience, life sciences that deals with anatomy, physiology, biochemistry or molecular biology of nerves and nervous tissue and especially with their relation to behavior and learning. I learned about synapse pre-synaptic and post-synaptic, especially neurotransmitter how it relates potential change." ^[learning neuroscience and behavior interactions]                                                                                                                                                          
 [2] "for today i learn about the short and long term of memory neuronal pools and long term potentiation."^[learning neuroscience of memory and neural networks]                                                                                                                                                                                                                                                                                                                                                                                       
 [3] "Today I learn potentiation which has to do with strengthening of synapse b/w nerve cell. I also learn about nature and nurture and how to deal with students in my school when they are finding it difficult to understand my lesson. I also learn about how memory can be lost and how they are retrieved."^[differentiating nature and nurture, learning memory formation]                                                                                                                                                                                
 [4] "I learned two major things among all (I) Long and short term memories. I learned that long term information are stored in the cortex.^[] While short term information are store in the hippocampus. (II) ^[learning memory and anatomy] I also learned about nature and nurture. Nature talkes about natural, while nurture talks about things we learn from the community."^[differentiating nature vs nurture]                                                                                                                                                  
 [5] "I did learn what it means by potentiation and depression, which has to do with strengthening synapse between nerve cell and reduction in the effectiveness of synapse and two what it means by short term memory (hippocampus things that you can't remember when you were young and things you still remember or long-term memory - cortex)" ^[learning plasticity and neuroscience of learning]                                                                                                                                                
 [6] "meaning of some neuroscience terms like potentiation, depression. How neurons are get more due to more impulses being received, vice versa. ^[learning plasticity] The types of circuit that can be formed from the movement of nerves fibers as: diverging circuit, converging, reverberating and parallel after discharge.^[learning neural networks] Nature vs. nurture"                                                                                                                                                                    
 [7] "I learned about long and short term potentiation as basis of memory and also I learn about the parts of the brain responsible for memory."^[learning memory formation and neuroanatomy]                                                                                                                                                                                                                                                                                                                                                 
 [8] "I learned about the long term and short term memory. I also learned about long term potentiation and short term potentiation. Short term memory is stored in hippocampus, while long term memory is stored in the cortex."^[learning memory formation and neuroanatomy]                                                                                                                                                                                                                                                                  
 [9] "I learn more new method of teaching my students."                                                                                                                                                                                                                                                                                                                                                                                                                                           
[10] "divergence, reverberation, neuronal pool, convergence. Nature and nurture and the loss of memory."                                                                                                                                                                                                                                                                                                                                                                                          
[11] "neuronal- as a group of neurons. Types of neuronal pools - diverging circuit (one nerve fiber branch to move) - converging circuit- input from many nerve fibers to one. Reverberating circuit send an axon vellateral back (feedback mechanism) parallel after discharge circuit. Nature and nurture."                                                                                                                                                                                     
[12] "In today's workshop we learnt about longterm memory and short term memory, critical response, critical response protocol, epigenetics, and neuronal pools and circuits. Nature and nurture."                                                                                                                                                                                                                                                                                                
[13] "I learned about neuronal pools, its two types of connections, the diverging and converging connections. How the brain works in terms of memory the long term potentiation and short term memory. Lastly, I learn on how nature and nurture are two different words and the two are key to transforming a student behavior and learning processes."                                                                                                                                          
[14] "From today lesson, I learned about two types of memory that they brain encode.They are the long time potentiation (long term memory) and short term potentiation ( short term memory). ^[differentiating memory formation processes] We were told about nature and nurture, from my understanding nature have to do with an inborn tenacity where as nurture has to do with things learned through another encouragement."^[differentiating nature vs nurture and the source of behaviors]                                                                                                                
[15] "on the third day of this workshop, I learned mostly about the parts of the brain and the function. We discussed that the brain is the central point of the body. Also, I learned how teachers deal with students in the classroom. The teachers should love students in the way to solve problems^["teachers should love students in the way to solve problems"] either in school to be able to meet their goals which is education. Never you put stress on students, let students that you teach be or treat them like the way you handle your children."^["treat them like the way you handle your children"]

[16] "I learned the following topics today: Nature vs Nurture, Reborn vs learnt lessons, heredity vs environment, creating mutuality, cantural vs orientation, developing relationship, prioritizing relationships, prioritizing others (students), recency and primacy."^[reborn vs learnt lessons]                                                                                                                                                                                                                         
[17] "I learn about potentiation involving long term and short term."                                                                                                                                                                                                                                                                                                                                                                                                                             
[18] "Today I learn about the brain and how it works. "                                                                                                                                                                                                                                                                                                                                                                                                                                            
[19] "long term and short term potentiation, emotional development, neuroscience of memory and stress"                                                                                                                                                                                                                                                                                                                                                                                             
[20] "I learn about between teachers and students relationship good, relationship between students and teachers make students to get good learning."^["relationship between students and teachers make students to get good learning"]                                                                                                                                                                                                                                                                                                                                              
[21] NA    

## Day 3, Question 2, "How will you apply this to your teaching?"

 [1] "apply to my teaching in that every information gathering will go across to my students"^["go across to my students]                                                                                                                          
 [2] "It applies to me as a teacher I should be able to make a great change into my students day by day."                                                                                                               
 [3] "This will apply to my teaching in the positive aspect because from this lesson today I have been educated on how to relate to bad and good student with in and out of my environment."^[relating to bad and good students, inclusive teaching]                           
 [4] "In my teaching I will take into consideration that my students behaviors are affected by both nature and nurture habits."^[considering student behavior in a new way]                                                                                        
 [5] "It has educated me how to be a moderate with my students when them and to created a friendship with my students and identified my students problems and how to solve some of them."^["how to be a moderate with my students]                              
 [6] "This application of this to my teaching is to make me nurture students with difficulties in different ways."^[applying nature vs nurture to student behavior]                                                                                                     
 [7] "It also give me a new idea to help students who have problems to be free from their problem or stress."^[contributing to student mental health]                                                                                                          
 [8] "It will help me to encourage students and other learners to encourage themselves with new words, balance, diets and avoid being stressed out. I will also recap my day one lessons during day two presentations."^[avoiding stress, recurring topics for memory formation]
 
   
 [9] "it applies to us as teachers you always there for their students."                                                                                                                                               
[10] "trained teachers should be able to nurture his students so that equal learning activity can be balanced."^[applying relationship building to the classroom for learning equity]                                                                                                        
[11] "This process will be apply by putting my students in group work, class activities and also their memory reflection (image, diagram, etc)"^[applying memory formation knowledge to classroom]                                                                         
[12] "At the end of today's session we realized all these neuractivities play a major role in the learning process between teacher and student since it all has to do with the brain or memory."^[learning process betweent teacher and student"]                       
[13] "I should be a teacher assess to be able to identify students problems in class and how to deal with them."^[assessing and dealing with problems"]                                                                                                       
[14] "In respect to how this can be applied to the classroom, I need to encourage my students too by creating a friendship learning environment so that the students can express their own feeling."^[motivating students with relationship, "creating a friendship learning environment"]                   
[15] NA                                                                                                                                                                                                                 
[16] "In a sense like, I've no known lots of things about the above topics and now I have the challenge to teach my students new things."^[teaching new things, experiencing the challenge of something new]                                                                              
[17] "It can be applied to the students based on their learning ability in and out of the classroom."                                                                                                                  
[18] "It helps me to build a good relationship with my students and people around me"^[relationship building]                                                                                                                                   
[19] "it will make my teaching more sophisticated and I can give new approach to them."                                                                                                                                
[20] "It make me to improve my student learning."                                                                                                                                                                      
[21] NA   
## Day 3, Question 3, "How will you respond to students who have learning difficulties?"  

 [1] "I create room to motivate my students such as class participation, group work, individual work."^["Create roome to motivate my students"]                                                                                                                                                                                      
 [2] "My response to my students as a good teacher I must be there to make the right things happen"^[being present]                                                                                                                                                                                           
 [3] "From today's lecture I have been educated on how to respond to students who have difficulty in learning from this I will always respond to these students in a very positive manner by nurturing them in the positive aspect."                                                         
 [4] "I will respond to students with difficulties by serving as a counsellor."^["serving as a counsellor", role expanding]                                                                                                                                                                                                              
 [5] "-change my method of teaching, motivating my students to have a high self-esteem."^[building self-esteem]                                                                                                                                                                                                     
 [6] "I could respont to them as: Advising them of the importance of education, creating an atmosphere to nurture them."^[advising and nurturing]                                                                                                                                                                     
 [7] "I will respond to students who have difficulty in learning by counseling them and bringing them closer to me as a teacher."^["bringing them closer"]                                                                                                                                                           
 [8] "I will go closer to them to understand their problem and help them overcome."^["go closer to them", teaching problem navigation]                                                                                                                                                                                                          
 [9] "My response to students who have difficulty in learning is to get close to them and to find the problems that they are faced with, because teacher are stakeholders of students."^["get close to them", finding problems]                                                                                                     
[10] "I response to students who have difficulty in learning by creating good learning environment."                                                                                                                                                                                         
[11] "Teacher and students relationship in the classroom which makes these students who have difficulties in learning to move forward. Proper evaluation of student will me the low learner to learn very fast."                                                                               
[12] "Students that have difficulties in learning maybe attributed to domestic problems stress or drug abuse.^[seeing sources of learning difficulties in home problems] As a professional teacher, my role is to cross-examine the students to find out the source of his/her problem and then help in a way that will improve their learning ability."^[investigating student problems]
[13] "engage them with the material always, be a counselor to them, encourage them in doing their own works." ^["engage, counsel and encourage"]                                                                                                                                                                                
[14] "I respond to student with difficulties in learning by getting connected, creating confidentiality and by putting my self in their situation."^["getting connected", "putting myself in their situation", practicing empathy and building relationship]                                                                                                                                          
[15] NA                                                                                                                                                                                                                                                                                       
[16] "In my own portion of teachings I respond to my students who have difficulty in learning the following ways: By bringing them closer to me, by creating a room for love for them, by having that cordious relation with them and so many more."^["bringing them closer", "creating a room for love for them"]                                         
[17] "I used motivational process where they need some encouragement."^[motivating and encouraging]                                                                                                                                                                                                                       
[18] "Based on the training that I get today I will apply those steps that I learn in the workshop."                                                                                                                                                                                         
[19] "The best thing to do is to nurture the student and get rid of his/her difficulty."^[nurturing and finding the root of problems]                                                                                                                                                                                                     
[20] "This student needs to be talked to"^[communicating]                                                                                                                                                                                                                                                    
[21] NA


## Day 4, Question 1, "What did you learn today?"  
  
 [1] "I learned about the human brain and it function"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 [2] "The class today I learned about certain parts of the function of the brain but the main part is in the brain, the frontal lobe, the executive part which help you to think."^[learning neuroanatomy]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 [3] "I did learn how information flow from one neuron to another very fast (excitatory) and how they are blocked. I also learn how synapses change a mindset and help you to as a teacher to be moderate with your students."^["how synapses change a mindset", being moderate with students]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
 [4] "1) about the autonomic nervous system (ANS). Whish is said to be the internal organs of living organisms. In addition it consists of two main parts they are sympathetic and parasympathetic.^[learning ANS and PNS] Sympathetic is the fight or flight while parasympathetic is all about rest and ingest. 2) I also learned about fixed and growth mindset (synapses change). Fixed mindset is where students don't believe in them or their ability. While growth mindset is where a student believe his/her ability. They study their lessons, in so doing their mind develops or grows."^["growth mindset is where a student believe his/her ability", understanding growth mindset]                                                                                                                                                                                                                                                                   
 [5] "I learn about follow up, action plan b/w two neuron from axon to dendrites, that is excitation and inhibition resulted in potential changes (synapses). I learned about human brain development and connection (synapse)."^[learning about development and plasticity]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [6] "I learned that during the transistion of child development, from childhood to adulthood (adolescent), the brain tends to development. Some of the development is the reduction in size of the grey matter in the brain which results in the reduction of unwanted synapses."^[learning brain and human development]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 [7] "In today's workshop, we learnt about the ANS and its functions in line with hypothalamus. We also learned about the post traumatic stress disorder or nervous disorders. We also demonstratedan activity to know how the neurons multiply or increases during complex activities using playing cards. We also learned about excitation and inhibition changes. We learned about fixed mindset and growing mind set. Finally we get to realize that every stage in our lives the brain undergoes development."^["every stage in our lives the brain undergoes development"]                                                                                                                                                                                                                                                                                                                            
 [8] "from today lesson, I learned several things. The ANS, this system is further divided into two categories and they are the sympathetic and parasympathetic, furthermore, they have an antagonistic response that is one increase the internal body function and another decreases that internal body function. Additionally, we also learned about PTSD. This can lead to human death. There are stages that come as a result of post traumatic stress disorder, which includes lonliness, failure, rejection, etc. I learned about the transportation of action potential and lastly, we were taught how adolescent brain development."^[learning about neuroanatomy, PTST and development]                                                                                                                                                                                                  
 [9] "I really enjoyed the growth mindset. The growth mindset starts with the teacher. A trained teacher should be able to create good environment for the students to learn. He or she should be able to give praises and rewards for good work done by the students."^["create a good environment for the students to learn", giving praise and rewarding]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[10] "for today's lesson I learned several things such as: Autonomic nervous system and post traumatic stress disorder, what causes psychiatric illness, and a growth mindset. Excitation and inhibition."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
[11] "For today I learned about teaching a growth mindset, PTSD defined, action potential and potential change, symptoms of autonomic neuropathy and also fight or flight. "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
[12] "I learned about the fight or flight response and rest or digest and PTSD. I learned about excitation and inhibition. Too much excitation causes illnesses in the body and also too much inhibition causes prone. I learned about potential change."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[13] "I learned how to becaome a good leader and also how to treat our students, to show them love whenever we see them sad."^["show them love whenever we see them sad"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
[14] "(a) Growth mindset - I learned ho one can be excited to learn when they receive praises,^["one can be excited to learn when the receive praises"] awards and courage. (b) the autonomic nervous sytem that controls the body functions such as breathing, heartbeat, and the digestive system. (c) the sympathetic nervous system (SNS) that is responsible for fight (danger or physical attack) or flight (the escape from danger). (d) the role of the ANS in emotional regulations, amygdala ( the center for emotional processing). (e) the symptoms of autonomic neuropathy, like: constipation, diarrhea, swallowing problems, etc. (f) the treatments of autonomic neuropathy (drinking enough water, adding salt to your diet). (g) lastly, I learned about the post-traumatic stress disorder PTSD that is caused by flashbacks, terrifying events either by experiencing or witnessing." 
[15] "Today I learned about the autonomic nervous system and the post traumatic stress disorder. Today I learned about how PTSD conditions occur and how to function with in our mind. They are situations that are difficult to cure."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[16] "When I go back to my school, I should do better, for these students that will be treating with it. To make them better students."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
[17] "About the parkinson's disease- degeneration disorder of the CNS. Sympathetic nervous system (SNS) which deal with fight or flight. Parasympathetic nervous system (PNS) which deal with rest and recuperation. hypothalamus- which regulate pulse, blood pressure, breathing and arousal in response. Growth mindset. How information flow from one neuron to another."^[learning anatomy and neurosystems]                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[18] "I learned about nervous system and neuroscience of emotion. Fight or flight. I learn about adolescent brain."^["neuroscience of emotion"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[19] "From today's lesson, I learned about the following points: A) autonomic nervous system- i.e. it controls and regulates the internal organs without any conscious effort by the organism B) two antagonistic set of nerves are sympathetic and parasympathetic nervous system. C) Epigenetic- study of heritable phenotype change that do not involve alterations of the DNA sequence. D) Excitation -(Magnetic) provided with an electrical generator or alternator. Inhibition - a feeling that make onself conscious."                                                                                                                                                                                                                                                                                                                 
[20] "I learned that our synapses fire out more when we engage ourselves into more activities. I learned about autonomic Nervous System and the neuroscience of emotions flight or fight. Growth mindset, excitation and inhibition, potential changes, beans drop with goggles adolescent brain development."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
[21] "I have learned that mental health is more important then people see it to be.^["mental health is important"] Mental health promotes mental wellness and active learning in the classroom. That students can only learn if they are mentally well and this can be promoted by the intervention of teachers and administration staff."^["students can only learn if they are mentally well", teachers playing a role in mental health]
  
## Day 4, Question 2, "How will you apply this to your teaching?"
   
[1] "It apply to my teaching, and it apply them it will make me a good teacher. And I will understand the ways of my students and to react to them."^["understand the ways"]                                                                                                                                                                                                
 [2] "I also learned the brain develop when the child frontal lobe is not developed their action is not accepted because they do not behave better you have to teach them."^[connecting behavior and development]                                                                                                                                                                          
 [3] "As a teacher it has changed mindset of how to be motivating, moderate, and engaging your students into activities that they can be someone."^["mindset of being motivating, moderate and engaging", "they can be someone"]                                                                                                                                                                                                    
 [4] "As a teacher i will work hard with my students especially the ones with a fix mindset. In doing this I will encourage, reward and give them confidence in the subject."^[utilising positive behavioral systems.]                                                                                                                                                                        
 [5] "Apply a lot to my teaching in that, I will be able to help make one to be as strong as the other. I will be able to motivate, encourage my students to put in more time."^[using positive reinforcement to motivate students]                                                                                                                                                                      
 [6] "In the classroom, students of adolescent age are to be looked after carefully because their brains are not fully developed.^[connecting behavior and normal development] Their thinking may be different from the classroom activities."                                                                                                                                                    
 [7] "With these informations, it will help us guide our students the right way and even identify some of the problems they are faced with."^[guiding students, identifying problems]                                                                                                                                                                                                          
 [8] "In respect to my teaching, I have taken time over the period to interact with my students through creating conducive interactive behavior."                                                                                                                                                                                                     
 [9] NA                                                                                                                                                                                                                                                                                                                                               
[10] "It also helps to improve my teaching by changing the attitude of the students to do the right thing in promoting quality education."^[changing attitude of students]                                                                                                                                                                                                           
[11] "I should first have a growth mindset that all students have equal rights.^[learning about student equality] I should also be able to communicate with my students when it comes to my lesson and other problems out of school work."^[being able to communicate]                                                                                                                                             
[12] "These ideas will actually help me to change my mindset in the classroom about those students that find it difficult to learn faster."^["help me change my mindset"]                                                                                                                                                                                                          
[13] "It improves my teaching and gives me more knowledge and make me to get more ideas on how to teach my students."                                                                                                                                                                                                                               
[14] "Firstly, as a teacher, I should have the mindset that students learning depends on my ability to encourage them into the learning process."^[connecting learning outcomes and encouragement]                                                                                                                                                                                                    
[15] "Today's lesson will help me to improve greatly in my study. Because I have that the more study we do the more our mind improves and we become stronger."^[learning plasticity and growth mindset]                                                                                                                                                                                      
[16] NA                                                                                                                                                                                                                                                                                                                                               
[17] "This is apply to my teaching by encouraging my students in order to take their lessons seriously. Telling my students to know there is nothing impossible for their learning"^["there is nothing impossible for their learning"]                                                                                                                                                                  
[18] "It will help me to be able to understand students and know that their brains are not fully mature."^[integrating development into relational understanding]                                                                                                                                                                                                                                            
[19] "From these lessons, my teaching will be upgraded, in that, I will applied these ideas to my teaching."                                                                                                                                                                                                                                         
[20] "It applies to my teaching in that, I have the privilege to inspire new knowledges to pass onto my students."                                                                                                                                                                                                                                  
[21] "At my school, I will promote mental health by establishing a team of instructors,^[promoting mental health at school] briefing them with what I have acquired ^[sharing info with school] and carrying on classroom friendly learning.^["classroom friendly learning"] That students should work in group and all should participate in classroom activities and the at each student should be looked at in the classroom of their activities."  

## Day 4, Question 3, "How will you respond to students with learning difficulties?"
  
[1] "I responded to them by marking them to understand and knowing their values" ^["knowing their values]                                                                                                                 
 [2] NA                                                                                                                                                                                           
 [3] NA                                                                                                                                                                                           
 [4] NA                                                                                                                                                                                           
 [5] NA                                                                                                                                                                                           
 [6] NA                                                                                                                                                                                           
 [7] NA                                                                                                                                                                                           
 [8] NA                                                                                                                                                                                           
 [9] NA                                                                                                                                                                                           
[10] "My response to students who have difficulty in learning will go like this: by creating student-centered, talking to the students in the right way that he or she will improve in learning."^[utilizing student-centered teaching techniques and relationship-building to improve learning outcomes]
[11] "As a good teacher, you should always be in the place of making way out of no way,^["making way out of no way"] also make them to realize that their effort in school is very important to you as a teacher."^[letting students know that their success is important to the teacher"]            
[12] NA                                                                                                                                                                                           
[13] "To always call them and advise them to take their lesson serious."^[advising]                                                                                                                         
[14] NA                                                                                                                                                                                           
[15] NA                                                                                                                                                                                           
[16] NA                                                                                                                                                                                           
[17] NA                                                                                                                                                                                           
[18] NA                                                                                                                                                                                           
[19] NA                                                                                                                                                                                           
[20] NA                                                                                                                                                                                           
[21] NA                                                                                                                                                                                           





